// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wthtnekwvqybutrtxhcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0aHRuZWt3dnF5YnV0cnR4aGNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzI2ODEsImV4cCI6MjA2MjkwODY4MX0.wiCfUJB2ghk1L2t8zr2vkBgiizG0XPaafGOtWXHLDMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);